version: '3.8'

volumes:
  rabbitmqData:
  rabbitmqLogData:
  postgres_data:
services:
  rabbitmq:
    image: rabbitmq:3.11.1-management
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=vhost
    volumes:
      - rabbitmqData:/var/lib/rabbitmq/ 
      - rabbitmqLogData:/var/log/rabbitmq
      - ${PWD}/docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ${PWD}/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ${PWD}/docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ${PWD}/docker/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - etl_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3      
  postgres:
    image: postgres:latest
    command:
      - postgres
      - -p 5432
      - "-c"
      - "max_connections=160"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "work_mem=6400kB"
      - "-c"
      - "maintenance_work_mem=100MB"
      - "-c"
      - "effective_cache_size=2500MB"
      - "-c"
      - "random_page_cost=1.0"
      - "-c"
      - "seq_page_cost=1.0"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    networks:
      - etl_network
  debezium:
    image: quay.io/debezium/server:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker/debezium/conf:/debezium/conf
      - ./docker/debezium/data:/debezium/data
    environment:
      - database.ssl.mode=disable
      - DEBEZIUM_TRUSTED_CERTIFICATES=trustServerCertificate=true
    networks:
      - etl_network
networks:
  etl_network:
    driver: bridge
