default_notion: &default_notion
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('PG_NOTION_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('PG_NOTION_PORT') { 5432 } %>
  username: <%= ENV.fetch('PG_NOTION_USER') { 'debezium' } %>
  password: <%= ENV.fetch('PG_NOTION_PASS') { 'debezium123' } %>

notion_development:
  <<: *default_notion  
  database: <%= ENV.fetch('PG_NOTION_DB', 'notion_dev') %>

notion_test:
  <<: *default_notion
  database: 'notion_test'

notion_production:
  <<: *default_notion
  database: <%= ENV.fetch('PG_NOTION_DB', '') %>

default_destination: &default_destination
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 }.to_i + 1 %>
  host: <%= ENV.fetch('PG_MB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('PG_MB_PORT') { 5432 } %>
  username: <%= ENV.fetch('PG_MB_USER') { 'destination' } %>
  password: <%= ENV.fetch('PG_MB_PASS') { 'destination123 } %>

mb_development:
  <<: *default_destination
  adapter: postgis
  database: <%= ENV.fetch('PG_MB_DB') { 'destination_development' } %>

mb_test:
  <<: *default_destination
  database: 'destination_test'

mb_staging:
  <<: *default_destination
  host: <%= ENV.fetch('X_PG_HOST') { '' } %>
  port: <%= ENV.fetch('X_PG_PORT') { 5432 } %>
  database: <%= ENV.fetch('X_PG_DB') { 'destination_staging' } %>
  username: <%= ENV.fetch('X_PG_USER') { '' } %>
  password: <%= ENV.fetch('X_PG_PASS') { '' } %>

mb_production:
  <<: *default_destination
  host: <%= ENV.fetch('X_PG_HOST') { '' } %>
  port: <%= ENV.fetch('X_PG_PORT') { 5432 } %>
  database: <%= ENV.fetch('X_PG_DB') { 'destination_production' } %>
  username: <%= ENV.fetch('X_PG_USER') { '' } %>
  password: <%= ENV.fetch('X_PG_PASS') { '' } %>
