default_source: default_source
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('PG_SOURCE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('PG_SOURCE_PORT') { 5432 } %>
  username: <%= ENV.fetch('PG_SOURCE_USER') { 'debezium' } %>
  password: <%= ENV.fetch('PG_SOURCE_PASS') { 'debezium123' } %>

source_development:
  <<: default_source  
  database: <%= ENV.fetch('PG_SOURCE_DB', 'source_dev') %>

source_test:
  <<: default_source
  database: 'source_test'

source_production:
  <<: default_source
  database: <%= ENV.fetch('PG_SOURCE_DB', '') %>

default_destination: &default_destination
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 10 }.to_i + 1 %>
  host: <%= ENV.fetch('PG_DST_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('PG_DST_PORT') { 5432 } %>
  username: <%= ENV.fetch('PG_DST_USER') { 'destination' } %>
  password: <%= ENV.fetch('PG_DST_PASS') { 'destination123 } %>

destination_development:
  <<: *default_destination
  adapter: postgis
  database: <%= ENV.fetch('PG_DST_DB') { 'destination_development' } %>

destination_test:
  <<: *default_destination
  database: 'destination_test'

destination_staging:
  <<: *default_destination
  host: <%= ENV.fetch('X_PG_HOST') { '' } %>
  port: <%= ENV.fetch('X_PG_PORT') { 5432 } %>
  database: <%= ENV.fetch('X_PG_DB') { 'destination_staging' } %>
  username: <%= ENV.fetch('X_PG_USER') { '' } %>
  password: <%= ENV.fetch('X_PG_PASS') { '' } %>

destination_production:
  <<: *default_destination
  host: <%= ENV.fetch('X_PG_HOST') { '' } %>
  port: <%= ENV.fetch('X_PG_PORT') { 5432 } %>
  database: <%= ENV.fetch('X_PG_DB') { 'destination_production' } %>
  username: <%= ENV.fetch('X_PG_USER') { '' } %>
  password: <%= ENV.fetch('X_PG_PASS') { '' } %>
